### ISSUE TITLE
mksquashfs: -force-gid invalid gid or unknown group

### ISSUE THREAD

**Issue by JeffCarpenter** [facebookincubator/xar#39]
I just ran ` make_xar --python /usr/lib/python3.7/site-packages/IPython --output ipython.xar` on Manjaro Linux (Arch derivative) and got this output:

```
make_xar --python /usr/lib/python3.7/site-packages/
IPython --output ipython.xar                                                                     
2019-11-12 21:01:04,679 INFO Squashing /tmp/tmpgk_12zc1 to /tmp/tmp4pyijqfo
mksquashfs: -force-gid invalid gid or unknown group      
Traceback (most recent call last):                                                               
  File "/home/redacted/.local/bin/make_xar", line 10, in <module>
    sys.exit(main())                                                                             
  File "/home/redacted/.local/lib/python3.7/site-packages/xar/make_xar.py", line 147, in main
    xar.build(opts.output, squashfs_options)                                                     
  File "/home/redacted/.local/lib/python3.7/site-packages/xar/xar_builder.py", line 269, in build
    self._staging, tmp_xar, self._shebang, xar_header, squashfs_options
  File "/home/redacted/.local/lib/python3.7/site-packages/xar/xar_builder.py", line 224, in _build_st
aging_dir                                                                                        
    xar.go()
  File "/home/redacted/.local/lib/python3.7/site-packages/xar/xar_util.py", line 104, in go
    subprocess.check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mksquashfs', '/tmp/tmpgk_12zc1', '/tmp/tmp5mqduxu2', '-
noappend', '-noI', '-noX', '-force-uid', 'nobody', '-force-gid', 'nogroup', '-b', '262144', '-com
p', 'gzip']' returned non-zero exit status 1.
```

**Comment by cooperlees** [comment]
Do you have a user ‘nobody’ and a ‘nobody’ group. If not please add, and, I guess we should add this requirement to the docs.

That is, that we expect both a nobody group and user to exist.

**Comment by JeffCarpenter** [comment]
Yeah, my distro was missing nogroup, so creating it cleared that up. I do think a nod to that possibility in the docs would be helpful (especially for the less Linux savvy).

**Comment by cooperlees** [comment]
Glad that was all the simple fix was. PR to the docs are welcome. Otherwise one of us will eventually add it.

**Comment by danieldjewell** [comment]
Actually, per the [current Linux LSB Refspecs](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/usernames.html) the correct user/group name is "nobody"... 

"nogroup" appears to be a deviation that some distributions use - Arch Linux does not appear to be one of them.

Given that the Linux/*NIX ecosystem is somewhat pluricentric - insofar as for _some_ things there aren't clear standards (and even when there are, one cannot safely assume that they're followed)... 

>That is, that we expect both a nobody group and user to exist.

And that's fine - I think they do in most cases. But they're not always called `nobody:nogroup`... And I'm not sure that there's a good way to determine on each system what that user is. (I mean with `root` it's easy ... it's *always* uid/gid `0`...)
